import { Router } from 'express';
import { autenticar, permitir } from '../middlewares/authMiddleware.js';
import * as c from '../controllers/crudController.js';
const router = Router();
router.use(autenticar);
router.get('/usuarios', permitir('ADMIN'), c.listarUsuarios);
router.post('/usuarios', permitir('ADMIN'), c.criarUsuario);
router.get('/alunos', permitir('ADMIN', 'INSTRUTOR'), c.listarAlunos);
router.post('/alunos', permitir('ADMIN'), c.criarAluno);
router.get('/instrutores', permitir('ADMIN'), c.listarInstrutores);
router.post('/instrutores', permitir('ADMIN'), c.criarInstrutor);
router.get('/planos', permitir('ADMIN', 'INSTRUTOR'), c.listarPlanos);
router.post('/planos', permitir('ADMIN'), c.criarPlano);
router.put('/planos/:id', permitir('ADMIN'), c.atualizarPlano);
router.delete('/planos/:id', permitir('ADMIN'), c.deletarPlano);
router.get('/treinos', permitir('ADMIN', 'INSTRUTOR', 'ALUNO'), c.listarTreinos);
router.post('/treinos', permitir('ADMIN', 'INSTRUTOR'), c.criarTreino);
router.get('/frequencias', permitir('ADMIN', 'INSTRUTOR'), c.listarFrequencias);
router.post('/frequencias', permitir('ADMIN', 'INSTRUTOR'), c.registrarFrequencia);
router.get('/pagamentos', permitir('ADMIN'), c.listarPagamentos);
router.post('/pagamentos', permitir('ADMIN'), c.criarPagamento);
export default router;
