/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FrequenciaRouteImport } from './routes/frequencia'
import { Route as AlunosIndexRouteImport } from './routes/alunos/index'
import { Route as AlunosListaRouteImport } from './routes/alunos/lista'
import { Route as AlunosNovoRouteImport } from './routes/alunos/novo'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingProntoRouteImport } from './routes/onboarding/pronto'
import { Route as PerfilIndexRouteImport } from './routes/perfil/index'
import { Route as PerfilAcademiaRouteImport } from './routes/perfil/academia'
import { Route as PerfilSegurancaRouteImport } from './routes/perfil/seguranca'
import { Route as RelatoriosIndexRouteImport } from './routes/relatorios/index'
import { Route as RelatoriosNovoRouteImport } from './routes/relatorios/novo'
import { Route as FinanceiroDespesasNovaRouteImport } from './routes/financeiro/despesas/nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FrequenciaRoute = FrequenciaRouteImport.update({
  id: '/frequencia',
  path: '/frequencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosIndexRoute = AlunosIndexRouteImport.update({
  id: '/alunos/',
  path: '/alunos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosListaRoute = AlunosListaRouteImport.update({
  id: '/alunos/lista',
  path: '/alunos/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosNovoRoute = AlunosNovoRouteImport.update({
  id: '/alunos/novo',
  path: '/alunos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProntoRoute = OnboardingProntoRouteImport.update({
  id: '/onboarding/pronto',
  path: '/onboarding/pronto',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilAcademiaRoute = PerfilAcademiaRouteImport.update({
  id: '/perfil/academia',
  path: '/perfil/academia',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilSegurancaRoute = PerfilSegurancaRouteImport.update({
  id: '/perfil/seguranca',
  path: '/perfil/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosIndexRoute = RelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosNovoRoute = RelatoriosNovoRouteImport.update({
  id: '/relatorios/novo',
  path: '/relatorios/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroDespesasNovaRoute = FinanceiroDespesasNovaRouteImport.update({
  id: '/financeiro/despesas/nova',
  path: '/financeiro/despesas/nova',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/frequencia': typeof FrequenciaRoute
  '/alunos/lista': typeof AlunosListaRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/onboarding/pronto': typeof OnboardingProntoRoute
  '/perfil/academia': typeof PerfilAcademiaRoute
  '/perfil/seguranca': typeof PerfilSegurancaRoute
  '/relatorios/novo': typeof RelatoriosNovoRoute
  '/alunos/': typeof AlunosIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/relatorios/': typeof RelatoriosIndexRoute
  '/financeiro/despesas/nova': typeof FinanceiroDespesasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/frequencia': typeof FrequenciaRoute
  '/alunos/lista': typeof AlunosListaRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/onboarding/pronto': typeof OnboardingProntoRoute
  '/perfil/academia': typeof PerfilAcademiaRoute
  '/perfil/seguranca': typeof PerfilSegurancaRoute
  '/relatorios/novo': typeof RelatoriosNovoRoute
  '/alunos': typeof AlunosIndexRoute
  '/financeiro': typeof FinanceiroIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/relatorios': typeof RelatoriosIndexRoute
  '/financeiro/despesas/nova': typeof FinanceiroDespesasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/frequencia': typeof FrequenciaRoute
  '/alunos/lista': typeof AlunosListaRoute
  '/alunos/novo': typeof AlunosNovoRoute
  '/onboarding/pronto': typeof OnboardingProntoRoute
  '/perfil/academia': typeof PerfilAcademiaRoute
  '/perfil/seguranca': typeof PerfilSegurancaRoute
  '/relatorios/novo': typeof RelatoriosNovoRoute
  '/alunos/': typeof AlunosIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/relatorios/': typeof RelatoriosIndexRoute
  '/financeiro/despesas/nova': typeof FinanceiroDespesasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/frequencia'
    | '/alunos/lista'
    | '/alunos/novo'
    | '/onboarding/pronto'
    | '/perfil/academia'
    | '/perfil/seguranca'
    | '/relatorios/novo'
    | '/alunos/'
    | '/financeiro/'
    | '/onboarding/'
    | '/perfil/'
    | '/relatorios/'
    | '/financeiro/despesas/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/frequencia'
    | '/alunos/lista'
    | '/alunos/novo'
    | '/onboarding/pronto'
    | '/perfil/academia'
    | '/perfil/seguranca'
    | '/relatorios/novo'
    | '/alunos'
    | '/financeiro'
    | '/onboarding'
    | '/perfil'
    | '/relatorios'
    | '/financeiro/despesas/nova'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/frequencia'
    | '/alunos/lista'
    | '/alunos/novo'
    | '/onboarding/pronto'
    | '/perfil/academia'
    | '/perfil/seguranca'
    | '/relatorios/novo'
    | '/alunos/'
    | '/financeiro/'
    | '/onboarding/'
    | '/perfil/'
    | '/relatorios/'
    | '/financeiro/despesas/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FrequenciaRoute: typeof FrequenciaRoute
  AlunosListaRoute: typeof AlunosListaRoute
  AlunosNovoRoute: typeof AlunosNovoRoute
  OnboardingProntoRoute: typeof OnboardingProntoRoute
  PerfilAcademiaRoute: typeof PerfilAcademiaRoute
  PerfilSegurancaRoute: typeof PerfilSegurancaRoute
  RelatoriosNovoRoute: typeof RelatoriosNovoRoute
  AlunosIndexRoute: typeof AlunosIndexRoute
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  RelatoriosIndexRoute: typeof RelatoriosIndexRoute
  FinanceiroDespesasNovaRoute: typeof FinanceiroDespesasNovaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frequencia': {
      id: '/frequencia'
      path: '/frequencia'
      fullPath: '/frequencia'
      preLoaderRoute: typeof FrequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/': {
      id: '/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AlunosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/lista': {
      id: '/alunos/lista'
      path: '/alunos/lista'
      fullPath: '/alunos/lista'
      preLoaderRoute: typeof AlunosListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/novo': {
      id: '/alunos/novo'
      path: '/alunos/novo'
      fullPath: '/alunos/novo'
      preLoaderRoute: typeof AlunosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/pronto': {
      id: '/onboarding/pronto'
      path: '/onboarding/pronto'
      fullPath: '/onboarding/pronto'
      preLoaderRoute: typeof OnboardingProntoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/academia': {
      id: '/perfil/academia'
      path: '/perfil/academia'
      fullPath: '/perfil/academia'
      preLoaderRoute: typeof PerfilAcademiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/seguranca': {
      id: '/perfil/seguranca'
      path: '/perfil/seguranca'
      fullPath: '/perfil/seguranca'
      preLoaderRoute: typeof PerfilSegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/': {
      id: '/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof RelatoriosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/novo': {
      id: '/relatorios/novo'
      path: '/relatorios/novo'
      fullPath: '/relatorios/novo'
      preLoaderRoute: typeof RelatoriosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/despesas/nova': {
      id: '/financeiro/despesas/nova'
      path: '/financeiro/despesas/nova'
      fullPath: '/financeiro/despesas/nova'
      preLoaderRoute: typeof FinanceiroDespesasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FrequenciaRoute: FrequenciaRoute,
  AlunosListaRoute: AlunosListaRoute,
  AlunosNovoRoute: AlunosNovoRoute,
  OnboardingProntoRoute: OnboardingProntoRoute,
  PerfilAcademiaRoute: PerfilAcademiaRoute,
  PerfilSegurancaRoute: PerfilSegurancaRoute,
  RelatoriosNovoRoute: RelatoriosNovoRoute,
  AlunosIndexRoute: AlunosIndexRoute,
  FinanceiroIndexRoute: FinanceiroIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  RelatoriosIndexRoute: RelatoriosIndexRoute,
  FinanceiroDespesasNovaRoute: FinanceiroDespesasNovaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
